name: Release

permissions: {}

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Release
    uses: grafana/xk6/.github/workflows/extension-release.yml@v1.1.4
    permissions:
      contents: write
    with:
      go-version: "1.24.x"
      os: '["linux"]'
      arch: '["amd64"]'
      k6-version: "v1.2.3"
      xk6-version: "1.1.4"

  register-version:
    name: Register Version
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Register version in k6 extension registry
        uses: pablochacin/k6-extension-registry/actions/register-version@main
        with:
          token: $${{ secrets.K6_EXTENSION_REGISTRY_UPDATER_CLIENT_SECRET }}
          module: github.com/pablochacin/xk6-example
          version: ${{ github.ref_name }}
          repository-url: ${{ github.server_url }}/${{ github.repository }}
          release-url: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}
