name: Release

permissions: {}

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Release
    uses: grafana/xk6/.github/workflows/extension-release.yml@v1.1.4
    permissions:
      contents: write
    with:
      go-version: "1.24.x"
      os: '["linux"]'
      arch: '["amd64"]'
      k6-version: "v1.2.3"
      xk6-version: "1.1.4"

  register-version:
    name: Register Version
    needs: release
    permissions:
      contents: write
      pull-requests: write
    uses: pablochacin/k6-extension-registry/.github/workflows/register-version.yml@main
    with:
      module: github.com/pablochacin/xk6-example
      version: ${{ github.ref_name }}
    secrets:
        app_id: ${{ secrets.K6_EXTENSION_REGISTRY_UPDATER_ID }}
        app_pem: ${{ secrets.K6_EXTENSION_REGISTRY_UPDATER_PEM }}

  # check the status of the register version workflow
  check-status:
    name: check register version status
    runs-on: ubuntu-latest
    needs: register-version
    if: always()
    steps:
      - name: Verify job passed
        run: |
          if [ "${{ needs.register-version.result }}" != "success" ]; then
            echo "register-version job failed with status: ${{ needs.register-version.result }}"
            exit 1
          fi
